### ISSUE TITLE
CSS not applied

### ISSUE THREAD

**Issue by guizmo** [target/react-native-svg-parser#10]
Hi there

I am passing my CSS string in the second parameter but it does not seem to work
	    <View>
	      { ReactNativeSvgParser(fileString, `path: { fill: #444; }`, {width: 80, height: 80}) }
	    </View>

Am i doing it wrong ?

**Comment by richaagrawal12** [comment]
@guizmo can you please share your code, how you implement it. 
I am facing this error "Unable to resolve "react-native-svg-parser" from "src\Router.js".

**Comment by a-r-d** [comment]
@guizmo yes you need to pass it as a string. e.g. -

```javascript
import ReactNativeSvgParser from 'react-native-svg-parser'

const svgString = `<svg height="100" width="100">
  <circle cx="50" cy="50" r="40" class="red-circle" />
</svg> 
`
const cssString = `
.red-circle {
  fill: red;
  stroke: black;
  stroke-width: 3;
}
`

const svgNode = ReactNativeSvgParser(svgString, cssString)



```

**Comment by a-r-d** [comment]
closing this, please see example, and I will add this more explicit example to the readme
